version: '3.8'
services:
  mysql-container:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - /Users/shawn/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
